// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB35LBM2yz4dRVYp53NRaBHnpSqFd0f9L8',
    appId: '1:796566485442:web:ef23c29d4d46f4c9f83e5b',
    messagingSenderId: '796566485442',
    projectId: 'pointage-d36f1',
    authDomain: 'pointage-d36f1.firebaseapp.com',
    storageBucket: 'pointage-d36f1.firebasestorage.app',
    measurementId: 'G-M72ZP67Q2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK0qRY1lvJxzd85IE4QpTshMmzjq6cDQo',
    appId: '1:796566485442:android:8c72c50f8ab2ca94f83e5b',
    messagingSenderId: '796566485442',
    projectId: 'pointage-d36f1',
    storageBucket: 'pointage-d36f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb1oumJ0fWCHm8d__xsyuQiuHUd9YpiFE',
    appId: '1:796566485442:ios:bdbfea769f94ce65f83e5b',
    messagingSenderId: '796566485442',
    projectId: 'pointage-d36f1',
    storageBucket: 'pointage-d36f1.firebasestorage.app',
    iosBundleId: 'com.soulfall.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb1oumJ0fWCHm8d__xsyuQiuHUd9YpiFE',
    appId: '1:796566485442:ios:6aed62c0e7d3c18ff83e5b',
    messagingSenderId: '796566485442',
    projectId: 'pointage-d36f1',
    storageBucket: 'pointage-d36f1.firebasestorage.app',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB35LBM2yz4dRVYp53NRaBHnpSqFd0f9L8',
    appId: '1:796566485442:web:c6f932b777415cb5f83e5b',
    messagingSenderId: '796566485442',
    projectId: 'pointage-d36f1',
    authDomain: 'pointage-d36f1.firebaseapp.com',
    storageBucket: 'pointage-d36f1.firebasestorage.app',
    measurementId: 'G-T9FJXP6GRM',
  );
}
